name: Build oxc-node
description: Build an oxc-node checkout using cargo
inputs:
  dir:
    description: Directory where oxc-node is checked out
    required: true

runs:
  using: "composite"
  steps:
    - name: Build with cargo
      shell: msys2 {0}
      run: |
        cd "${{ inputs.dir }}"
        RS_TARGET_ARCH=$(rustc -vV | grep '^host:' | awk '{print $2}')
        cargo build --release --target $RS_TARGET_ARCH
